name: CodeBuild Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::971416076373:role/GitHubActionsOIDC-CodeBuildTest
        aws-region: ap-northeast-1

    - name: Run CodeBuild
      uses: aws-actions/aws-codebuild-run-build@v1.0.18
      with:
        project-name: react-github-actions-project